### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Bampocalypse** [voxeltycoon/issues#1034]
![image](https://user-images.githubusercontent.com/132455094/235902781-b27fdb26-0ca8-4c12-97c0-58e534ff38ad.png)
I have been playing with some mods, and this error message has been appearing.
I have disabled all the mods I was using but that didn't do anything.
If anyone has any advice, I would gladly take it.

**Comment by andrewpey** [comment]
It seems that the problem is definitely related to mods. 

Even if you have disabled all the mods, there might be some script mods that continue to run even after disabling them. To completely disable script mods, you need to restart the game.

Let me know if you experience the problem even after restarting the game.

**Comment by Bampocalypse** [comment]
Hi.
Thanks for the advice.
I will get back to you when i can.
