### ISSUE TITLE
Steam Discussions Moderators Are Hurting More Than Helping

### ISSUE THREAD

**Issue by aminecraftplayerx** [voxeltycoon/issues#732]
I've been trying to figure out some problems I have been having through the Steam forums. You have a couple of moderators on there that have been described at "more argumentative than helpful". I have to wholeheartedly agree with that sentiment. You might consider that they're probably causing you to lose sales and to have people refund sales.

**Comment by voxeltycoon** [comment]
We are sorry you feel this way, but we see that our community moderators doing a damn good job helping us and players answering questions on Steam forums, Discord, and anywhere else they can.  Without them, our two-man team would be just buried in organizing communication instead of developing the game further.

If you want to suggest improvements to gameplay or seek help with the game, please [open a discussion](https://github.com/voxeltycoon/issues/discussions). Please look if the same issue wasn't raised already.

Have a nice day!
