### ISSUE TITLE
Game/Unity crashes randomly and closes my game

### ISSUE THREAD

**Issue by DaDonut** [voxeltycoon/issues#796]
**Describe the bug**
Randomly when I'm playing the game, a Unity Voxel Tycoon crash screen will pop up and crash my game. This happens for no reason as I can tell, sometimes I'll just be idly watching the flow of traffic and it will crash, and other times I'll be laying down roads.

I have updated my graphics drivers and uninstalled the game with no fix.
![4ec9c9014bfb978f3b8472980606ec43](https://user-images.githubusercontent.com/57339251/119204302-b9164700-ba5a-11eb-954e-bd9ed84a4225.png)

**Steps to reproduce**
I'm not sure, just play the game

**Build version**
0.86.0.0 Steam

**Platform**
Windows 10

**Reproducibility**
It happens randomly for no reason, sometimes I can play for hours and nothing happens. Other times it crashes 4 times in 30 minutes.

**Logs/saves**
[Player.log](https://github.com/voxeltycoon/issues/files/6525323/Player.log)

**Comment by CasianoKoprowski** [comment]
Hello! I thought I'd plus one this issue, but I'll add that it's pretty similar to #764 as well.  Unlike the OP in this ticket and more like #764, I rarely get more than 10-20 minutes of playtime per session.  Sometimes it crashes immediately after loading into a game.  The save included has Steam Workshop mods enabled, but this issue was present before I installed any mods.

**Steps to reproduce**
Play the game.  Sometimes it seems like it's related to placing infrastructure (buildings, roads/tracks) and sometimes it just happens.  

**Build version**
0.86.0.0 Steam

**Platform**
Windows 10

**Reproducibility**
Playing the game for any amount of time will result in the crash

**Logs/saves**
[20210608_Player-prev.log](https://github.com/voxeltycoon/issues/files/6641676/20210608_Player-prev.log)

**Comment by MrKiel** [comment]
Same!

Appears to me a Unity access violation. 
Putting the crash.dmp through a debugger shows no useful information, unfortunately (that I can see, anyway). 

`*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************


KEY_VALUES_STRING: 1

    Key  : AV.Fault
    Value: Read

    Key  : Analysis.CPU.Sec
    Value: 0

    Key  : Analysis.DebugAnalysisProvider.CPP
    Value: Create: 8007007e on DESKTOP-1VHU5O4

    Key  : Analysis.DebugData
    Value: CreateObject

    Key  : Analysis.DebugModel
    Value: CreateObject

    Key  : Analysis.Elapsed.Sec
    Value: 0

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 231

    Key  : Analysis.System
    Value: CreateObject

    Key  : Timeline.Process.Start.DeltaSec
    Value: 1583


CONTEXT:  (.ecxr)
rax=000080007ea841f9 rbx=0000009b8d1feca0 rcx=00007fff86250000
rdx=0000009b8d1fecd0 rsi=00000252910b90c0 rdi=0000009b8d1fedc0
rip=00007fff87143cfc rsp=0000009b8d1fea58 rbp=0000009b8d1feb60
 r8=0000000000000008  r9=00000000579bbb93 r10=0000009b8d1fecd0
r11=0000000000000038 r12=0000009b8d1fec48 r13=0000000000000000
r14=0000009b8d1fed00 r15=00000252910b8bc0
iopl=0         nv up ei pl nz na po nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010206
UnityPlayer!UnityMain+0x9c21ec:
00007fff`87143cfc ffe0            jmp     rax {00008000`7ea841f9}
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007fff87143cfc (UnityPlayer!UnityMain+0x00000000009c21ec)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: ffffffffffffffff
Attempt to read from address ffffffffffffffff

PROCESS_NAME:  VoxelTycoon.exe

READ_ADDRESS:  ffffffffffffffff 

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  ffffffffffffffff

STACK_TEXT:  
0000009b`8d1fea58 00007fff`86a2e538 : 00000252`9113a400 00000251`f09f3990 0000009b`8d1febc8 00007fff`86aec329 : UnityPlayer!UnityMain+0x9c21ec
0000009b`8d1fea60 00007fff`86a31f93 : 00000000`00000671 00000000`00000000 0000009b`8d1fedc8 0000009b`8d1feca0 : UnityPlayer!UnityMain+0x2aca28
0000009b`8d1febe0 00007fff`86a31433 : 0000009b`8d1ff078 00000252`91044dd0 00000252`910b8bc0 0000009b`8d1fedc0 : UnityPlayer!UnityMain+0x2b0483
0000009b`8d1fed50 00007fff`86a29ca3 : 00000252`910b8bc0 0000009b`8d1ff078 00000000`00000000 00000252`73de4538 : UnityPlayer!UnityMain+0x2af923
0000009b`8d1fef40 00007fff`869ea302 : 00000000`00000000 00000252`73de4520 00000251`f09f3900 0000009b`8d1ff150 : UnityPlayer!UnityMain+0x2a8193
0000009b`8d1ff050 00007fff`869e9f33 : 00000251`f09f3950 00000252`73de4520 00000000`00000000 00000252`91044dd0 : UnityPlayer!UnityMain+0x2687f2
0000009b`8d1ff210 00007fff`8687037f : 00000000`00000000 0000009b`8d1ff7e0 00000252`73de4520 00000000`00000000 : UnityPlayer!UnityMain+0x268423
0000009b`8d1ff300 00007fff`868745ce : 00000254`522b0a40 0000009b`8d1ff4d0 00000251`f09f3950 00000251`f05b3a20 : UnityPlayer!UnityMain+0xee86f
0000009b`8d1ff3d0 00007fff`8672e55c : 00000251`f09f3920 00000251`f05af610 00000253`109b2201 00000000`0000000a : UnityPlayer!UnityMain+0xf2abe
0000009b`8d1ffab0 00007fff`86983536 : 00000252`701dee90 00000252`701dee00 00000253`d55234f0 00000000`0789af73 : UnityPlayer+0x4de55c
0000009b`8d1ffb00 00007fff`86983a67 : 00000000`00000000 ffffffff`ffffffff 00000253`d55234f0 00000000`00000000 : UnityPlayer!UnityMain+0x201a26
0000009b`8d1ffb50 00007fff`86984f80 : 00000000`00000000 00000252`701dee90 00000000`00000000 00000252`701df2b0 : UnityPlayer!UnityMain+0x201f57
0000009b`8d1ffb90 00007fff`86a787d8 : 00000252`701df2b0 00000252`701df2b0 00000000`00000000 00000000`00000000 : UnityPlayer!UnityMain+0x203470
0000009b`8d1ffbc0 00007fff`cacc7034 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : UnityPlayer!UnityMain+0x2f6cc8
0000009b`8d1ffbf0 00007fff`cc4c2651 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
0000009b`8d1ffc20 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21


SYMBOL_NAME:  UnityPlayer!UnityMain+9c21ec

MODULE_NAME: UnityPlayer

IMAGE_NAME:  UnityPlayer.dll

STACK_COMMAND:  ~8s ; .ecxr ; kb

FAILURE_BUCKET_ID:  INVALID_POINTER_READ_c0000005_UnityPlayer.dll!UnityMain

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {3b9c28c0-1d4c-cec8-a9be-c0d87d1c3f85}

Followup:     MachineOwner
---------
`

[crash.zip](https://github.com/voxeltycoon/issues/files/6736781/crash.zip)
[error.log](https://github.com/voxeltycoon/issues/files/6736779/error.log)
[Player.log](https://github.com/voxeltycoon/issues/files/6736780/Player.log)

**Comment by CasianoKoprowski** [comment]
Just wanted to add that this continues for me in 0.86.1 after I noticed that patch note that read: "Unity updated to 2020.3.12"

**Comment by MrKiel** [comment]
Withdrawing my +1. 

In my case, Unity is crashing under oddly specific conditions present in XMP-overclocked RAM at 3200Mhz. To be clear: there's nothing wrong with the RAM, the issue lies with either the XMP profile being 'too loose' or Unity introducing unique failure conditions that other applications / game engines do not. 

Source used for troubleshooting [here](https://forum.unity.com/threads/unityplayer-dll-every-games-made-with-it-are-randomly-crashing.897173/)

My solution [here](https://forum.kerbalspaceprogram.com/index.php?/topic/203570-unity-crashing-access-violation/)

To summarise: It took me months to track this down, as I only recently realised that it was only Unity games, including this one, that were crashing with this error. I'm still not 100% sure it's a fix, given that I've had the problem for months and the crashes are not reproducible (seemingly random). However, I've had zero crashes in Unity games since my attempted fix, having played >10 hours of Voxel Tycoon and >10 hours of Kerbal without issues, which is far better than it was. 

I manually entered the RAM timings in the BIOS for 3200Mhz using Ryzen DRAM Calculator (see solution above), but choosing another XMP profile (not 3200Mhz) may also resolve the issue. 

Note that this affects both AMD and Intel CPU (see source thread linked above to Unity forums), Intel CPUs have a similar solution.

**Comment by MrKiel** [comment]
@CasianoKoprowski and @DaDonut hopefully the above will help you

**Comment by CasianoKoprowski** [comment]
Oh; interesting!  I'll have to set aside some time to read through everything and try this out.  Thanks for the find @MrKiel

**Comment by andrewpey** [comment]
Is the solution worked for you guys?

**Comment by DaDonut** [comment]
> Did the solution work for you guys?

I tried MrKiel’s solution but it didn’t seem to work, the same crash screen still happened

**Comment by andrewpey** [comment]
Sorry to hear this, still nothing points out to the problem with the game itselt, more like system/drivers/hardware issue. So, there's not much we can do with it, unfortunatelly.
